apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.ports.amqp }}
      targetPort: {{ .Values.service.ports.amqp }}
    - name: management
      port: {{ .Values.service.ports.management }}
      targetPort: {{ .Values.service.ports.management }}
  selector:
    app: rabbitmq
