replicaCount: 1

image:
  repository: rabbitmq
  tag: management
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    amqp: 5672
    management: 15672

rabbitmq:
  user: user
  password: bitnami

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
